AWSTemplateFormatVersion: '2010-09-09'
Description: "Child stack to create an IAM role."

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3ReadOnlyAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::cfbucket2025"
                  - "arn:aws:s3:::cfbucket2025/*"

Outputs:
  IAMRoleName:
    Description: "Name of the IAM role"
    Value: !Ref MyIAMRole
