AWSTemplateFormatVersion: '2010-09-09'
Description: "Child stack to create an S3 bucket."

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "my-bucket-${AWS::StackName}-${AWS::Region}"
      AccessControl: Private
      BucketEncryption:  # Optional: Enable server-side encryption
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:  # Optional: Block public access
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
  S3BucketRegionalDomainName:
    Description: "Regional domain name of the S3 bucket"
    Value: !GetAtt MyS3Bucket.RegionalDomainName

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket
