name: Deploy to S3

on:
  push:
    branches:
      - main
    paths:
     - 'NestedStacks/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Sync files to S3
        run: |
          aws s3 sync ./NestedStacks s3://${{ secrets.AWS_S3_BUCKET }}/
